<a href="https://colab.research.google.com/github/HimanshuSahoo/Himanshu_Python/blob/main/Recommendation_Rules_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("book.csv", encoding="ISO-8859-1")
df

      Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

In [4]:
df.columns

Index(['Unnamed: 0', 'User.ID', 'Book.Title', 'Book.Rating'], dtype='object')

In [5]:
df1=df.drop('Unnamed: 0',axis=1)
df1.head()

   User.ID                                         Book.Title  Book.Rating
0   276726                                Classical Mythology            5
1   276729                                       Clara Callan            3
2   276729                               Decision in Normandy            6
3   276736  Flu: The Story of the Great Influenza Pandemic...            8
4   276737                             The Mummies of Urumchi            6

In [6]:
df1.shape

(10000, 3)

In [7]:
df1.columns

Index(['User.ID', 'Book.Title', 'Book.Rating'], dtype='object')

In [8]:
df2=df1.rename({'User.ID':'user_id','Book.Title':'book_title','Book.Rating':'book_rating'},axis = 1)
df2

      user_id                                         book_title  book_rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [9]:
df2[df2.duplicated()]

      user_id                 book_title  book_rating
5051     2152  Le nouveau soleil de Teur            7
7439     3757        The Magician's Tale            7

In [10]:
df2[df2.duplicated()].shape

(2, 3)

In [11]:
df3=df2.drop_duplicates()
df3

      user_id                                         book_title  book_rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[9998 rows x 3 columns]

In [12]:
df3[df3.duplicated()].shape

(0, 3)

In [13]:
len(df3.user_id.unique())

2182

In [14]:
len(df3.book_title.unique())

9659

In [15]:
book_df=df3.pivot_table(index='user_id',
                 columns='book_title',
                 values='book_rating')

In [16]:
book_df

book_title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
user_id                           ...
8                            NaN  ...             NaN
9                            NaN  ...             NaN
10                           NaN  ...             NaN
12                           NaN  ...             NaN
14                           NaN  ...             NaN
...                          ...  ...             ...
278846                       NaN  ...             NaN
278849                       NaN  ...             NaN
278851                       NaN  ...             NaN
278852                       NaN  ...             NaN
278854                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [17]:
book_df.index=df3.user_id.unique()

In [18]:
book_df

book_title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
276726                       NaN  ...             NaN
276729                       NaN  ...             NaN
276736                       NaN  ...             NaN
276737                       NaN  ...             NaN
276744                       NaN  ...             NaN
...                          ...  ...             ...
162107                       NaN  ...             NaN
162109                       NaN  ...             NaN
162113                       NaN  ...             NaN
162121                       NaN  ...             NaN
162129                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [19]:
book_df.fillna(0,inplace=True)

In [20]:
book_df

book_title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
276726                       0.0  ...             0.0
276729                       0.0  ...             0.0
276736                       0.0  ...             0.0
276737                       0.0  ...             0.0
276744                       0.0  ...             0.0
...                          ...  ...             ...
162107                       0.0  ...             0.0
162109                       0.0  ...             0.0
162113                       0.0  ...             0.0
162121                       0.0  ...             0.0
162129                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [21]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [22]:
user_sim=1-pairwise_distances(book_df.values,metric='cosine')

In [23]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
usersim_df=pd.DataFrame(user_sim)

In [25]:
usersim_df

      0     1     2     3     4     5     ...  2176  2177  2178  2179  2180  2181
0      1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
1      0.0   1.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2      0.0   0.0   1.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3      0.0   0.0   0.0   1.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4      0.0   0.0   0.0   0.0   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
2177   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   1.0   0.0   0.0   0.0   0.0
2178   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0
2179   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   1.0   0.0   0.0
2180   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0
2181   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   1.0

[2182 rows x 2182 columns]

In [26]:
usersim_df.index = df3.user_id.unique()
usersim_df.columns = df3.user_id.unique()

In [27]:
usersim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [28]:
import numpy as np
np.fill_diagonal(user_sim, 0)
usersim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [29]:
usersim_df.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [30]:
df3[(df3['user_id']==276729) | (df3['user_id']==276726)]

   user_id            book_title  book_rating
0   276726   Classical Mythology            5
1   276729          Clara Callan            3
2   276729  Decision in Normandy            6

In [31]:
user1=df3[df3['user_id']==276729]

In [32]:
user2=df3[df3['user_id']==276726]

In [33]:
user1.book_title

1            Clara Callan
2    Decision in Normandy
Name: book_title, dtype: object

In [34]:
user2.book_title

0    Classical Mythology
Name: book_title, dtype: object

In [35]:
pd.merge(user1,user2,on='book_title',how='outer')

   user_id_x            book_title  book_rating_x  user_id_y  book_rating_y
0   276729.0          Clara Callan            3.0        NaN            NaN
1   276729.0  Decision in Normandy            6.0        NaN            NaN
2        NaN   Classical Mythology            NaN   276726.0            5.0